### ISSUE TITLE
Multiple timer

### ISSUE THREAD

**Issue by SteFR** [jrullan/neotimer#2]
Hi,

Nice library ! 

I have tried to use multiple timers (declaration seems ok) :

`for (int i = 0; i < 13; i++)
  {
      Neotimer timer[i] = Neotimer(temps[i]);
  }`

with times constants : 

`const unsigned int temps[13] = {2500, 2500, 2500, 3500, 3500, 2500, 2500, 2500, 2000, 2500, 2500, 2000, 2000};`

but when I call function :

 `timer[0].start();`

it doesn't work, compilator said :

> exit status 1
'timer' was not declared in this scope
> 

What have I miss understood ?

Is it possible to do that ?

Best regards,

Stéphane

**Comment by jrullan** [comment]
@SteFR,

I'm sorry I just saw this message. Just in case you are still interested I am sharing a test sketch I just wrote to try to troubleshoot your issue and this works. Some thoughts:

I would be cautious using a variable named just `timer` because it might be in use already by the framework or the Arduino internal libraries. Instead in this example I am using the variable `timers`. :warning: Remember to declare this variable as a global variable.

Also, make sure your array of timers scope is available to the `setup()` and the  `loop()` routine. I would assign the **Neotimer** instances in the `setup()` function as shown below.

Finally, the timers durations are expected to be of a **long** data type.

```c++
#include <neotimer.h>

Neotimer timers[2];
const long durations[] = {1000,5000};

void setup() {
  Serial.begin(9600);

  for(int i=0; i<2; i++){
    timers[i]= Neotimer(durations[i]);
    timers[i].start(); // Start the timer initially
  }
 
}

void loop(){
  
  for(int i=0; i<2; i++){
    
    if(timers[i].done()){
      Serial.print("Timer ");
      Serial.print(i);
      Serial.println(" done");
      timers[i].start(); // Start the done timer again.
    }
    
  }
}
```
